@startuml uml_seq_diagram_process
autonumber

participant Producer
participant Consumer
participant Storage
participant Solver

Group Add task
    Producer ->> Storage : AddTask
    return ticket
end

Group Get task
    Consumer ->> Storage : GetTask
    return ticket, task
end

Group Calculate and Save data
    Consumer ->> Solver : Solve
    return result

    Consumer ->> Storage : SaveResult
end

Group Retrieve data from cache
    Producer ->> Storage : GetResult
    return result
end
@enduml