@startuml uml_seq_diagram_process
autonumber

participant Producer
participant Consumer
participant Manager

Group Add task (loop)
    Producer ->> Manager : AddTask
    return flag (task was added or not)
    Opt Task was NOT added
        Producer -> Producer : wait
    end
end

Group Get task (loop)
    Consumer ->> Manager : GetTask
    Opt Fail to get task
        Consumer -> Consumer : wait
    end
end

Group Calculate and Save data
    Consumer ->> Manager : CalculateTask
    return answer

    Consumer ->> Manager : AddValue
end

Group Retrieve data from cache (loop)
    Producer ->> Manager : GetValue
    return value (null value if there is no value in cache)
    Opt null value
        Producer -> Producer : wait
    end
end
@enduml