@startuml uml_seq_diagram_process
autonumber

participant Producer
participant Queue
participant Consumer
participant Cache
participant Server

Group ThreadPool
Group Put task
    Producer ->> Cache: check Cache
    Opt Cache contains task with such id
        Producer -> Producer : proceed to the next task
    end
    Producer ->> Queue : put(task)
end

Opt Task was added to Queue
        Queue -> Consumer : notify
end

Opt Queue is NOT empty
        Consumer ->> Queue : get(task)
end

Group Caching
Consumer -> Cache : check Cache
opt Cahce does NOT contain data with such task id
  Consumer ->> Server : make a server request
  Server --> Consumer : receive response
  Consumer ->> Cache : save it to cache
end

end
end
@enduml